###
# This section is to define firewall rules
###

- include: ufw.yml
  when: UFW_DO_CONFIGURE

###
# This is the main section to install gateone
###
- name: install dependent packages
  apt: name="{{ item }}" update_cache=yes
  with_items:
    - python-pip
    - build-essential
    - python-dev
    - git
    - python-imaging
    - dtach
    - nginx

- name: clone the GateOne config
  git: repo="{{ GATEONE_CONFIG_REPO }}" dest=/opt/gateone-config accept_hostkey=yes
  notify: restart gateone

- name: link nginx config file
  file: src="/opt/gateone-config/gateone-ssl-nginx.conf" dest="/etc/nginx/sites-enabled/default" state=link
  notify: restart nginx

- name: clone the nginx config for gateone
  git: repo="https://github.com/cyverse/nginx_gateone_config.git" dest=/opt/nginx_gateone_config accept_hostkey=yes
  notify: restart nginx

- name: ensure locations directory exists
  file: dest="/etc/nginx/locations" state=directory

- name: link nginx gateone file
  file: src="/opt/nginx_gateone_config/gateone-nginx-location.conf" dest="/etc/nginx/locations/gateone-nginx-location.conf" state=link
  notify: restart nginx

- name: link the certficate file
  file: src="{{SSL_HOST_SRC}}/{{ item }}" dest="/etc/ssl/certs/{{ item }}" state=link force=yes
  with_items:
    - "{{ SSL_HOST_CERT }}"
  notify: restart apache

- name: link the key file
  file: src="{{SSL_HOST_SRC}}/{{ SSL_HOST_KEY }}" dest="/etc/ssl/private/{{ SSL_HOST_KEY }}" state=link force=yes
  notify: restart apache

- name: install pip packages
  pip: name="{{ item }}"
  with_items:
    - tornado

- name: clone the GateOne source
  git: repo="{{ GATEONE_REPO }}" dest=/opt/GateOne accept_hostkey=yes
  notify: restart gateone

- name: setup install GateOne
  shell: python setup.py install chdir=/opt/GateOne

- name: install the systemd service
  file: src=/opt/GateOne/scripts/init/gateone.service dest=/etc/systemd/system/gateone.service state=link

# commented out for now, but could be useful for generating new certs
#- name: generate the configuration file
#  shell: /usr/local/bin/gateone --configure creates=/etc/gateone/conf.d/10server.conf

- name: ensure conf directory exists
  file: dest="{{ item }}" state=directory
  with_items:
    - "/etc/gateone/conf.d/"
    - "/etc/gateone/ssl/"

- name: link configuration files for now
  file: src="/opt/gateone-config/{{ item }}" dest="/etc/gateone/conf.d/{{ item }}" state=link
  with_items:
    - 10server.conf
    - 20authentication.conf
    - 50terminal.conf
    - ssh_config_global

- name: link the source ssl files
  file: src="{{SSL_HOST_SRC}}/{{ item }}" dest="/etc/gateone/ssl/{{ item }}" state=link force=yes
  with_items:
    - "{{ SSL_HOST_KEY }}"
    - "{{ SSL_HOST_CERT }}"
  notify: restart gateone

- name: enable the gateone service
  service: name=gateone enabled=yes state=started
  notify: restart gateone
